In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\hp\Downloads\archive.zip")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [3]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [5]:
df.shape

(10000, 8)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [7]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [8]:
df.nunique()

Transaction ID      10000
Item                   10
Quantity                7
Price Per Unit          8
Total Spent            19
Payment Method          5
Location                4
Transaction Date      367
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Transaction ID"].duplicated().sum()

np.int64(0)

In [13]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [14]:
text_columns = ["Item", "Payment Method", "Location"]

for col in text_columns:
    df[col] = df[col].str.strip()

In [15]:
print(df["Item"].unique())
print(df["Payment Method"].unique())
print(df["Location"].unique())

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

In [16]:
cols = ["Item", "Payment Method", "Location"]

for col in cols:
    df[col] = df[col].replace(["UNKNOWN", "ERROR"], pd.NA)

In [17]:
df[["Item", "Payment Method", "Location"]].isnull().sum()

Item               969
Payment Method    3178
Location          3961
dtype: int64

In [18]:
print(df["Item"].unique())
print(df["Payment Method"].unique())
print(df["Location"].unique())

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',        nan,
 'Sandwich',    'Juice',      'Tea']
Length: 9, dtype: str
<StringArray>
['Credit Card', 'Cash', nan, 'Digital Wallet']
Length: 4, dtype: str
<StringArray>
['Takeaway', 'In-store', nan]
Length: 3, dtype: str

In [19]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      3178
Location            3961
Transaction Date     159
dtype: int64

In [20]:
df[["Quantity", "Price Per Unit", "Total Spent"]].describe()

       Quantity Price Per Unit Total Spent
count      9862           9821        9827
unique        7              8          19
top           5            3.0         6.0
freq       2013           2429         979

In [21]:
numeric_columns = ["Quantity", "Price Per Unit", "Total Spent"]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [22]:
df[["Quantity", "Price Per Unit", "Total Spent"]].dtypes

Quantity          float64
Price Per Unit    float64
Total Spent       float64
dtype: object

In [23]:
df[["Quantity", "Price Per Unit", "Total Spent"]].describe()

          Quantity  Price Per Unit  Total Spent
count  9521.000000     9467.000000  9498.000000
mean      3.028463        2.949984     8.924352
std       1.419007        1.278450     6.009919
min       1.000000        1.000000     1.000000
25%       2.000000        2.000000     4.000000
50%       3.000000        3.000000     8.000000
75%       4.000000        4.000000    12.000000
max       5.000000        5.000000    25.000000

In [24]:
df["Calculated Total"] = df["Quantity"] * df["Price Per Unit"]

df[["Quantity", "Price Per Unit", "Total Spent", "Calculated Total"]].head(10)

   Quantity  Price Per Unit  Total Spent  Calculated Total
0       2.0             2.0          4.0               4.0
1       4.0             3.0         12.0              12.0
2       4.0             1.0          NaN               4.0
3       2.0             5.0         10.0              10.0
4       2.0             2.0          4.0               4.0
5       5.0             4.0         20.0              20.0
6       3.0             3.0          9.0               9.0
7       4.0             4.0         16.0              16.0
8       5.0             3.0         15.0              15.0
9       5.0             4.0         20.0              20.0

In [25]:
comparison = df["Total Spent"] == df["Calculated Total"]

comparison.value_counts(dropna=False)

True     8544
False    1456
Name: count, dtype: int64

In [28]:
mismatch = df[
    df["Total Spent"].notna() &
    df["Calculated Total"].notna() &
    (df["Total Spent"] != df["Calculated Total"])
]

print("Mismatched rows:", len(mismatch))

Mismatched rows: 0

In [29]:
missing_total = df[
    df["Total Spent"].isna() &
    df["Quantity"].notna() &
    df["Price Per Unit"].notna()
]

print("Missing Total Spent with enough data:", len(missing_total))

Missing Total Spent with enough data: 462

In [30]:
df["Total Spent"] = df["Total Spent"].fillna(
    df["Quantity"] * df["Price Per Unit"]
)

In [31]:
df["Total Spent"].isna().sum()

np.int64(40)

In [32]:
df[["Quantity", "Price Per Unit"]].isnull().sum()

Quantity          479
Price Per Unit    533
dtype: int64

In [33]:
print(
    "Quantity recoverable:",
    df["Quantity"].isna().sum()
    - (df["Quantity"].isna() & df["Total Spent"].isna()).sum()
)

print(
    "Price Per Unit recoverable:",
    df["Price Per Unit"].isna().sum()
    - (df["Price Per Unit"].isna() & df["Total Spent"].isna()).sum()
)

Quantity recoverable: 459
Price Per Unit recoverable: 513

In [34]:
df["Calculated Quantity"] = (
    df["Total Spent"] / df["Price Per Unit"]
)

df["Calculated Price"] = (
    df["Total Spent"] / df["Quantity"]
)

In [37]:
print(df[[
    "Quantity",
    "Price Per Unit",
    "Total Spent",
    "Calculated Quantity",
    "Calculated Price"
]].isnull().sum())

Quantity               479
Price Per Unit         533
Total Spent             40
Calculated Quantity    553
Calculated Price       499
dtype: int64

In [38]:
print(df.loc[
    df["Quantity"].isna(),
    ["Quantity", "Price Per Unit", "Total Spent", "Calculated Quantity", "Calculated Price"]
].head(10))

     Quantity  Price Per Unit  Total Spent  Calculated Quantity  \
20        NaN             4.0         20.0                  5.0
55        NaN             1.0          2.0                  2.0
57        NaN             3.0          3.0                  1.0
66        NaN             3.0          6.0                  2.0
117       NaN             3.0          9.0                  3.0
153       NaN             3.0         12.0                  4.0
177       NaN             5.0         25.0                  5.0
178       NaN             4.0         16.0                  4.0
189       NaN             1.0          3.0                  3.0
198       NaN             3.0         12.0                  4.0

     Calculated Price
20                NaN
55                NaN
57                NaN
66                NaN
117               NaN
153               NaN
177               NaN
178               NaN
189               NaN
198               NaN

In [39]:
valid_quantity = df.loc[
    df["Quantity"].isna() & df["Calculated Quantity"].notna(),
    "Calculated Quantity"
]

print("Recoverable:", len(valid_quantity))
print("Non-integer:", (valid_quantity % 1 != 0).sum())
print("Below 1:", (valid_quantity < 1).sum())
print("Above 5:", (valid_quantity > 5).sum())

Recoverable: 441
Non-integer: 0
Below 1: 0
Above 5: 0

In [40]:
df["Quantity"] = df["Quantity"].fillna(
    df["Calculated Quantity"]
)

In [41]:
print(df["Quantity"].isna().sum())

38

In [42]:
valid_price = df.loc[
    df["Price Per Unit"].isna() & df["Calculated Price"].notna(),
    "Calculated Price"
]

print("Recoverable:", len(valid_price))
print("Non-integer:", (valid_price % 1 != 0).sum())
print("Below 1:", (valid_price < 1).sum())
print("Above 5:", (valid_price > 5).sum())

Recoverable: 495
Non-integer: 67
Below 1: 0
Above 5: 0

In [43]:
non_integer_prices = df.loc[
    df["Price Per Unit"].isna() &
    df["Calculated Price"].notna() &
    (df["Calculated Price"] % 1 != 0),
    ["Quantity", "Total Spent", "Calculated Price"]
]

print(non_integer_prices.head(20))

      Quantity  Total Spent  Calculated Price
85         3.0          4.5               1.5
196        2.0          3.0               1.5
289        4.0          6.0               1.5
333        1.0          1.5               1.5
334        4.0          6.0               1.5
441        1.0          1.5               1.5
550        4.0          6.0               1.5
757        4.0          6.0               1.5
1154       2.0          3.0               1.5
1379       3.0          4.5               1.5
1749       2.0          3.0               1.5
1786       4.0          6.0               1.5
1939       5.0          7.5               1.5
1988       4.0          6.0               1.5
2009       5.0          7.5               1.5
2191       5.0          7.5               1.5
2256       2.0          3.0               1.5
2344       5.0          7.5               1.5
2488       5.0          7.5               1.5
2506       4.0          6.0               1.5

In [44]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(
    df["Calculated Price"]
)

In [45]:
print(df["Price Per Unit"].isna().sum())

38

In [46]:
remaining_missing = df.loc[
    df["Quantity"].isna() |
    df["Price Per Unit"].isna() |
    df["Total Spent"].isna(),
    [
        "Transaction ID",
        "Quantity",
        "Price Per Unit",
        "Total Spent"
    ]
]

print(remaining_missing.head(20))
print("\nRows remaining:", len(remaining_missing))

     Transaction ID  Quantity  Price Per Unit  Total Spent
65      TXN_4987129       3.0             NaN          NaN
236     TXN_8562645       NaN             5.0          NaN
278     TXN_3229409       NaN             3.0          NaN
629     TXN_9289174       NaN             NaN         12.0
641     TXN_2962976       NaN             3.0          NaN
738     TXN_8696094       NaN             4.0          NaN
912     TXN_1575608       NaN             NaN         20.0
1008    TXN_7225428       NaN             NaN          3.0
1436    TXN_7590801       NaN             NaN          6.0
1482    TXN_3593060       NaN             NaN         16.0
1674    TXN_9367492       2.0             NaN          NaN
1761    TXN_3611851       4.0             NaN          NaN
2229    TXN_8498613       2.0             NaN          NaN
2289    TXN_7524977       4.0             NaN          NaN
2330    TXN_3849488       NaN             NaN          5.0
2585    TXN_1259340       3.0             NaN          NaN
2796    TXN_9188692       NaN             3.0          NaN
3162    TXN_3577949       3.0             NaN          NaN
3203    TXN_4565754       NaN             4.0          NaN
3224    TXN_6297232       NaN             2.0          NaN

Rows remaining: 58

In [47]:
print(
    df.loc[
        df["Quantity"].isna() &
        df["Price Per Unit"].isna() &
        df["Total Spent"].notna()
    ].shape[0],
    "rows: Total only"
)

print(
    df.loc[
        df["Quantity"].notna() &
        df["Price Per Unit"].isna() &
        df["Total Spent"].isna()
    ].shape[0],
    "rows: Quantity only"
)

print(
    df.loc[
        df["Quantity"].isna() &
        df["Price Per Unit"].notna() &
        df["Total Spent"].isna()
    ].shape[0],
    "rows: Price only"
)

print(
    df.loc[
        df["Quantity"].isna() &
        df["Price Per Unit"].isna() &
        df["Total Spent"].isna()
    ].shape[0],
    "rows: All three missing"
)

18 rows: Total only
20 rows: Quantity only
20 rows: Price only
0 rows: All three missing

In [48]:
print(df[[
    "Item",
    "Payment Method",
    "Location"
]].isna().sum())

Item               969
Payment Method    3178
Location          3961
dtype: int64

In [49]:
print("ITEM")
print(df["Item"].value_counts(dropna=False))

print("\nPAYMENT METHOD")
print(df["Payment Method"].value_counts(dropna=False))

print("\nLOCATION")
print(df["Location"].value_counts(dropna=False))

ITEM
Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
NaN          969
Name: count, dtype: int64

PAYMENT METHOD
Payment Method
NaN               3178
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

LOCATION
Location
NaN         3961
Takeaway    3022
In-store    3017
Name: count, dtype: int64

In [50]:
print(df["Transaction Date"].isna().sum())

159

In [51]:
print("Minimum date:", df["Transaction Date"].min())
print("Maximum date:", df["Transaction Date"].max())

print("\nMissing dates:", df["Transaction Date"].isna().sum())

Minimum date: 2023-01-01
Maximum date: UNKNOWN

Missing dates: 159

In [52]:
print(df["Transaction Date"].value_counts(dropna=False).tail(10))

Transaction Date
2023-05-12    16
2023-04-22    16
2023-08-08    16
2023-04-27    15
2023-11-24    15
2023-09-24    15
2023-07-30    15
2023-03-11    14
2023-07-22    14
2023-02-17    14
Name: count, dtype: int64

In [53]:
print("UNKNOWN:", (df["Transaction Date"] == "UNKNOWN").sum())
print("ERROR:", (df["Transaction Date"] == "ERROR").sum())
print("NaT:", df["Transaction Date"].isna().sum())

UNKNOWN: 159
ERROR: 142
NaT: 159

In [54]:
df["Transaction Date"] = df["Transaction Date"].replace(
    ["UNKNOWN", "ERROR"],
    pd.NaT
)

In [55]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    errors="coerce"
)

In [56]:
print("Missing dates:", df["Transaction Date"].isna().sum())
print("Minimum date:", df["Transaction Date"].min())
print("Maximum date:", df["Transaction Date"].max())
print("Data type:", df["Transaction Date"].dtype)

Missing dates: 460
Minimum date: 2023-01-01 00:00:00
Maximum date: 2023-12-31 00:00:00
Data type: datetime64[us]

In [57]:
df = df.drop(
    columns=[
        "Calculated Total",
        "Calculated Quantity",
        "Calculated Price"
    ]
)

In [58]:
print(df.isna().sum())

Transaction ID         0
Item                 969
Quantity              38
Price Per Unit        38
Total Spent           40
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [61]:
print("Duplicate Transaction IDs:", df["Transaction ID"].duplicated().sum())
print("\nFinal Dataset Info:")
print(df.info())

Duplicate Transaction IDs: 0

Final Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9031 non-null   str
 2   Quantity          9962 non-null   float64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9960 non-null   float64
 5   Payment Method    6822 non-null   str
 6   Location          6039 non-null   str
 7   Transaction Date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB
None

In [64]:
df.to_csv("clean_dataset.csv", index=False)

In [65]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,1.0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [66]:
import os
print(os.path.exists("clean_dataset.csv"))

True